#! /bin/sh

sxhkd & # x hotkey daemon
nm-applet & # network manager tray icon
xsetroot -cursor_name left_ptr # get rid of ugly x cursor
~/.config/bspwm/launch.sh polybar main # panel
~/.config/bspwm/launch.sh redshift-gtk # adjusts color temperature of screen

# bspc monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config
bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
